
version: '3.8'


services:
  app:
    build: .
    depends_on:
      - mongo
    container_name: docker-node-mongo
    restart: always
    env_file: ./.env
    ports:
      - '3000:3000'
    environment:
        - DB_HOST=mongo
        - DB_USER=admin
        - DB_PASSWORD=password


  mongo:
    container_name: mongo
    image: mongo:6.0.3  
    env_file: ./.env
    ports:
      - '27017:27017'
    environment:
          MONGO_INITDB_ROOT_USERNAME: admin
          MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - db/data/db

volumes:
  db:      


