version: "3"
services:
  backend:
    build: ./backend
    image: my-backend-image:latest
    container_name: my-backend-container
    ports:
      - '8000:8000'
    networks:
      - mynetwork

  client:
    build: ./client
    image: my-frontend-image:latest
    ports:
      - '3000:3000'
    networks:
      - mynetwork

  mongo:
    container_name: mongodb-container
    image: mongo:6.0.3  
    env_file: ./.env
    ports:
      - '27017:27017'
    environment:
      - DB_HOST=mongo
      - DB_USER=admin
      - DB_PASSWORD=password
    networks:
      - my_network
    volumes:
      - db/data/db

networks:
    my_network:
      driver: bridge

volumes:
  db: