---

  - name: Playbook
    hosts: all
    become: true
    gather_facts: true
    tasks:

      - name: check if path exits
        stat: 
          path: /home/vagrant/yolo
        register: yolo_exists

      - name: Checkout repository
        shell: git clone https://github.com/Esschichu/yolo.git
        when: not yolo_exists.stat.exists

        

      - name: Install dependencies
        become: true
        apt:
          name: "{{ packages }}"
          update_cache: yes
        vars:
          packages:
            - nodejs
            - npm
        

      - name: Frontend install required modules in package.json
        command: >
          chdir=/home/vagrant/yolo/client/
          npm install
          npm start
      

      - name: Install dependencies
        become: true
        apt:
          name: "{{ packages }}"
          update_cache: yes
        vars:
          packages:
            - mongodb-clients



      - name: Backend install required modules in package.json
        command: >
          chdir=/home/vagrant/yolo/backend/
          npm install
          npm start


        


          