apiVersion: v1
kind: Service
metadata:
 name: mongodb
 labels:
   tier:  dbstorage
spec:
 ports:
 - port: 27017
   targetPort: 27017
 selector:
   tier: dbstorage

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db
spec:

  replicas: 1
  serviceName: "dbstorage"
  selector:
    matchLabels:
      tier: dbstorage
  template:
    metadata:
      labels:
        tier: dbstorage
    spec:
      volumes:
        - name: mongodb-volume
          persistentVolumeClaim:
            claimName: yolo-pv-claim
      containers:
      - name: dbstorage
        image: achieng/my-backend-image
        ports:
        - containerPort: 27017
          name: db
        volumeMounts:
          - mountPath: "/data/db"
            name: mongodb-volume